name: Run go build and Scanning by Trivy vulnerability in repo mode
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Run go build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v2.2.0
      with:
        go-version: 1.13
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.4.0
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: go build -v ./cmd/utcg/
  scan:
    name: Scanning by Trivy vulnerability in repo mode
    runs-on: ubuntu-latest
    steps:
    - name: Run Trivy vulnerability scanner in repo mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        format: 'template'
        template: '@/contrib/sarif.tpl'
        output: 'trivy-results.sarif'
        severity: 'CRITICAL'
